### ISSUE TITLE
3.0 Alpha Voice Not Heared

### ISSUE THREAD

**Issue by InterSstellar** [CyberMor/sampvoice#38]
Hello i am using version 3.0 and my script is same as examples.
when the client hold z or b OnPlayerActivationKeyPress is called and SvAttachSpeakerToStream works but the sound cannot be heared by other clients.

please help me i really need this to work :(

**Comment by InterSstellar** [comment]
I Downgraded To 2.1 And it worked but the voice volume is too low and the voice is laggy

**Comment by darylreznov** [comment]
Are you sure you have the right client version?

**Comment by InterSstellar** [comment]
I'm Using SA-MP 0.3.7-R1,
I Fixed That Problem Somhow.

But There Is Another One.

Every Time A Listener Gets Out Of A Player Dynamic Local Stream Range The Voice Cuts But The Speaker Name Stays On The Speaker List Of The Listener.

I'm Trying To Fix It by myself but i don't know much about c++ and this project is a lot heavy for me xD
But anyways I'm trying to fix it.

**Comment by Hach-Trykach** [comment]
Did you solve the problem?
Please tell me how you did it

**Comment by EInterStellar** [comment]
@Hach-Trykach 

It was build issue.
I just cloned the repository and built the plugin again using visual studio community and it fixed the problem. You can download it from this [link](https://visualstudio.microsoft.com/vs/community/).

Because this plugin was made using [Plugin-SDK](https://github.com/DK22Pac/plugin-sdk) You have to follow the [instructions](https://github.com/DK22Pac/plugin-sdk/wiki) of [Plugin-SDK](https://github.com/DK22Pac/plugin-sdk) in order to build the this plugin.

I think u will also face #44 problem and if u want to fix it u have to edit the plugin by yourself and build it again ( Codes are available in the PR That I made ).
I'm not a C++ programmer so my code is not good. But it fixes the problem.

If you have any questions feel free to ask.

**Comment by Hach-Trykach** [comment]
Thanks for the clarification, I will try to do as you described.

I have 2 problems.
In version 3.0 I have no sound but everything else works.
And in version 3.1 there is sound but the pawn.raknet plugin that I need does not work.

I am trying to solve both problems.
